/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Status struct {
	Error_ bool `json:"error,omitempty"`
	Code int32 `json:"code,omitempty"`
	Type_ string `json:"type,omitempty"`
	Message string `json:"message,omitempty"`
}
