/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Mapping struct {
	Id int32 `json:"id,omitempty"`
	// The name of the mapping.
	Name string `json:"name"`
	// Indicates if the mapping is enabled or not.
	Enabled bool `json:"enabled"`
	// Indicates how conditions should be matched.
	Match string `json:"match"`
	// Indicates the order of the mapping. When `null` this will default to last position.
	Position int32 `json:"position"`
	// An array of conditions that the user must meet in order for the mapping to be applied.
	Conditions []Condition `json:"conditions,omitempty"`
	// An array of actions that will be applied to the users that are matched by the conditions.
	Actions []Action `json:"actions"`
}
