/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetScoreInsights200ResponseScores struct {
	Minimal int32 `json:"minimal,omitempty"`
	Low int32 `json:"low,omitempty"`
	Medium int32 `json:"medium,omitempty"`
	High int32 `json:"high,omitempty"`
	VeryHigh int32 `json:"very_high,omitempty"`
}
