/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenerateMfaTokenRequest struct {
	// Set the duration of the token in seconds.
	ExpiresIn string `json:"expires_in,omitempty"`
	// Defines if the token is reusable multiple times within the expiry window.
	Reusable bool `json:"reusable,omitempty"`
}
