/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenerateMfaToken200Response struct {
	// Token can function as a temporary MFA token. It can be used to authenticate for any app when valid.
	MfaToken string `json:"mfa_token,omitempty"`
	// true indcates the token can be used multiple times. false indicates the token is invalid after a single use
	Reusable bool `json:"reusable,omitempty"`
	// Defines the expiration time and date for the token. Format is UTC time.
	ExpiresAt string `json:"expires_at,omitempty"`
	// Defines the expiration time and date for the token. Format is UTC time.
	DeviceId string `json:"device_id,omitempty"`
}
