/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Array of factor specific properties. For example, the token or totp code for OneLogin Protect.
type FactorInnerFactorData struct {
	// The token which can be used to verify the factor registration.
	VerificationToken string `json:"verification_token,omitempty"`
	// OTP Url that can be leveraged for any authenticator that supports the key uri format.
	TotpUrl string `json:"totp_url,omitempty"`
}
