/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListConditions200ResponseInner struct {
	// The name of the Condition.
	Name string `json:"name,omitempty"`
	// The unique identifier of the condition. This should be used when defining conditions for a rule.
	Value string `json:"value,omitempty"`
}
