/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerifyFactorSaml200Response struct {
	// Provides the SAML assertion.
	Data string `json:"data,omitempty"`
	// Plain text description describing the outcome of the response.
	Message string `json:"message,omitempty"`
}
