/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddAccessTokenClaimRequest struct {
	Name string `json:"name,omitempty"`
	UserAttributeMappings string `json:"user_attribute_mappings,omitempty"`
	UserAttributeMacros string `json:"user_attribute_macros,omitempty"`
}
