/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetRiskScore200Response struct {
	// A risk score 0 is low risk and 100 is the highest risk level possible.
	Score float64 `json:"score,omitempty"`
	// Triggers are indicators of some of the key items that influenced the risk score.
	Triggers []string `json:"triggers,omitempty"`
}
