/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenerateMfaToken422Response struct {
	StatusCode int32 `json:"statusCode,omitempty"`
	Name string `json:"name,omitempty"`
	Message string `json:"message,omitempty"`
	Details *GenerateMfaToken422ResponseDetails `json:"details,omitempty"`
}
