/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ClientApp struct {
	AppId int32 `json:"app_id,omitempty"`
	ApiAuthId int32 `json:"api_auth_id,omitempty"`
}
