/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetRateLimit200Response struct {
	Status *Status `json:"status,omitempty"`
	Data *GetRateLimit200ResponseData `json:"data,omitempty"`
}
