/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetRateLimit200ResponseData struct {
	XRateLimitLimit int32 `json:"X-RateLimit-Limit,omitempty"`
	XRateLimitRemaining int32 `json:"X-RateLimit-Remaining,omitempty"`
	XRateLimitReset int32 `json:"X-RateLimit-Reset,omitempty"`
}
