/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Connector struct {
	// The connectors unique ID in OneLogin.
	Id int32 `json:"id,omitempty"`
	// The name of the connector.
	Name string `json:"name,omitempty"`
	AuthMethod *AuthMethod `json:"auth_method,omitempty"`
	// Indicates if apps created using this connector will be allowed to create custom parameters.
	AllowsNewParameters bool `json:"allows_new_parameters,omitempty"`
	// A link to the apps icon url.
	IconUrl string `json:"icon_url,omitempty"`
}
