/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Schema1 struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
	Username string `json:"username,omitempty"`
	AddedBy *Schema1AddedBy `json:"added_by,omitempty"`
	AddedAt string `json:"added_at,omitempty"`
	// Indicates if assigned to role or not. Defaults to true.
	Assigned bool `json:"assigned,omitempty"`
}
