/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Schema struct {
	// Apps unique ID in OneLogin.
	Id int32 `json:"id,omitempty"`
	// ID of the apps underlying connector.
	ConnectorId int32 `json:"connector_id,omitempty"`
	// App name.
	Name string `json:"name,omitempty"`
	// Freeform description of the app.
	Description string `json:"description,omitempty"`
	// Freeform notes about the app.
	Notes string `json:"notes,omitempty"`
	// The security policy assigned to the app.
	PolicyId int32 `json:"policy_id,omitempty"`
	// The custom login page branding to use for this app. Applies to app initiated logins via OIDC or SAML.
	BrandId int32 `json:"brand_id,omitempty"`
	// A link to the apps icon url.
	IconUrl string `json:"icon_url,omitempty"`
	// Indicates if the app is visible in the OneLogin portal.
	Visible bool `json:"visible,omitempty"`
	// An ID indicating the type of app.
	AuthMethod int32 `json:"auth_method,omitempty"`
	// ID of the OneLogin portal tab that the app is assigned to.
	TabId int32 `json:"tab_id,omitempty"`
	// The date the app was created.
	CreatedAt string `json:"created_at,omitempty"`
	// The date the app was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
	// List of Role IDs that are assigned to the app. On App Create or Update the entire array is replaced with the values provided.
	RoleIds []int32 `json:"role_ids,omitempty"`
	// Indicates whether or not administrators can access the app as a user that they have assumed control over.
	AllowAssumedSignin bool `json:"allow_assumed_signin,omitempty"`
	Provisioning *SchemaProvisioning `json:"provisioning,omitempty"`
	Sso *interface{} `json:"sso,omitempty"`
	Configuration *interface{} `json:"configuration,omitempty"`
	Parameters *interface{} `json:"parameters,omitempty"`
	EnforcementPoint *interface{} `json:"enforcement_point,omitempty"`
}
