/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type User struct {
	Id int32 `json:"id,omitempty"`
	// A username for the user.
	Username string `json:"username,omitempty"`
	// A valid email for the user.
	Email string `json:"email,omitempty"`
	// The user's first name.
	Firstname string `json:"firstname,omitempty"`
	// The user's last name.
	Lastname string `json:"lastname,omitempty"`
	// The user's job title.
	Title string `json:"title,omitempty"`
	// The user's department.
	Department string `json:"department,omitempty"`
	// The user's company.
	Company string `json:"company,omitempty"`
	// Free text related to the user.
	Comment string `json:"comment,omitempty"`
	// The ID of the Group in OneLogin that the user is assigned to.
	GroupId int32 `json:"group_id,omitempty"`
	// A list of OneLogin Role IDs of the user
	RoleIds []int32 `json:"role_ids,omitempty"`
	// The E.164 format phone number for a user.
	Phone string `json:"phone,omitempty"`
	State int32 `json:"state,omitempty"`
	Status int32 `json:"status,omitempty"`
	// The ID of the OneLogin Directory of the user.
	DirectoryId int32 `json:"directory_id,omitempty"`
	// The ID of the OneLogin Trusted IDP of the user.
	TrustedIdpId int32 `json:"trusted_idp_id,omitempty"`
	// The ID of the user's manager in Active Directory.
	ManagerAdId string `json:"manager_ad_id,omitempty"`
	// The OneLogin User ID for the user's manager.
	ManagerUserId string `json:"manager_user_id,omitempty"`
	// The user's Active Directory username.
	SamaccountName string `json:"samaccount_name,omitempty"`
	// The user's directory membership.
	MemberOf string `json:"member_of,omitempty"`
	// The principle name of the user.
	Userprincipalname string `json:"userprincipalname,omitempty"`
	// The distinguished name of the user.
	DistinguishedName string `json:"distinguished_name,omitempty"`
	// The ID of the user in an external directory.
	ExternalId string `json:"external_id,omitempty"`
	ActivatedAt string `json:"activated_at,omitempty"`
	LastLogin string `json:"last_login,omitempty"`
	InvitationSentAt string `json:"invitation_sent_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	PreferredLocaleCode string `json:"preferred_locale_code,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	CustomAttributes *interface{} `json:"custom_attributes,omitempty"`
	InvalidLoginAttempts int32 `json:"invalid_login_attempts,omitempty"`
	LockedUntil string `json:"locked_until,omitempty"`
	PasswordChangedAt string `json:"password_changed_at,omitempty"`
	// The password to set for a user.
	Password string `json:"password,omitempty"`
	// Required if the password is being set.
	PasswordConfirmation string `json:"password_confirmation,omitempty"`
	// Use this when importing a password that's already hashed. Prepend the salt value to the cleartext password value before SHA-256-encoding it
	PasswordAlgorithm string `json:"password_algorithm,omitempty"`
	// The salt value used with the password_algorithm.
	Salt string `json:"salt,omitempty"`
}
