/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
// AuthMethod : An ID indicating the type of app.
type AuthMethod int32

// List of auth_method
const (
	0__AuthMethod AuthMethod = "0"
	1__AuthMethod AuthMethod = "1"
	2__AuthMethod AuthMethod = "2"
	3__AuthMethod AuthMethod = "3"
	4__AuthMethod AuthMethod = "4"
	6__AuthMethod AuthMethod = "6"
	7__AuthMethod AuthMethod = "7"
	8__AuthMethod AuthMethod = "8"
)
