/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// An Object containing User details.
type RiskUser struct {
	// A unique identifier for the user.
	Id string `json:"id"`
	// A name for the user.
	Name string `json:"name,omitempty"`
	// Indicates if the metadata supplied in this event should be considered as trusted for the user.
	Authenticated bool `json:"authenticated,omitempty"`
}
