/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerifyFactorSamlRequest struct {
	// App ID of the app for which you want to generate a SAML token. This is the app ID in OneLogin.
	AppId string `json:"app_id"`
	// Provide the MFA device_id you are submitting for verification. The device_id is supplied by the Generate SAML Assertion API.
	DeviceId string `json:"device_id"`
	// state_token associated with the MFA device_id you are submitting. The state_token is supplied by the Generate SAML Assertion API.
	StateToken string `json:"state_token"`
	// Provide the OTP value for the MFA factor you are submitting for verification.
	OtpToken string `json:"otp_token,omitempty"`
	// When verifying MFA via Protect Push, set this to true to stop additional push notifications being sent to the OneLogin Protect device.
	DoNotNotify bool `json:"do_not_notify,omitempty"`
}
