/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenerateToken200Response struct {
	AccessToken string `json:"access_token,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	ExpiresIn int32 `json:"expires_in,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	TokenType string `json:"token_type,omitempty"`
	AccounttId int32 `json:"accountt_id,omitempty"`
}
