/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Condition struct {
	// The source field to check.
	Source string `json:"source,omitempty"`
	// A valid operator for the selected condition source
	Operator string `json:"operator,omitempty"`
	// A plain text string or valid value for the selected condition source.
	Value string `json:"value,omitempty"`
}
