/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetClientApps200ResponseInnerScopesInner struct {
	Description string `json:"description,omitempty"`
	Value string `json:"value,omitempty"`
	Id int32 `json:"id,omitempty"`
}
