/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListActions200ResponseInner struct {
	// The name of the Action.
	Name string `json:"name,omitempty"`
	// The unique identifier of the action. This should be used when defining actions for a User Mapping.
	Value string `json:"value,omitempty"`
}
