/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ActivateFactorRequest struct {
	// Required. Specifies the factor to be verified.
	DeviceId int32 `json:"device_id,omitempty"`
	// Optional. Sets the window of time in seconds that the factor must be verified within. 
	ExpiresIn int32 `json:"expires_in,omitempty"`
	// Optional. Only applies to Email MagicLink factor.
	RedirectTo string `json:"redirect_to,omitempty"`
	// Optional. Only applies to SMS factor. A message template that will be sent via SMS.
	CustomMessage string `json:"custom_message,omitempty"`
}
