/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetUserApps200ResponseInner struct {
	// The App ID
	Id int32 `json:"id,omitempty"`
	// A url for the icon that represents the app in the OneLogin portal
	IconUrl string `json:"icon_url,omitempty"`
	// Boolean that indicates if the OneLogin browser extension is required to launch this app.
	Extension bool `json:"extension,omitempty"`
	// Unqiue identifier for this user and app combination.
	LoginId int32 `json:"login_id,omitempty"`
	// The name of the app.
	Name string `json:"name,omitempty"`
	ProvisioningStatus string `json:"provisioning_status,omitempty"`
	// If provisioning is enabled this indicates the state of provisioning for the given user.
	ProvisioningState string `json:"provisioning_state,omitempty"`
	// Indicates if provisioning is enabled for this app.
	ProvisioningEnabled bool `json:"provisioning_enabled,omitempty"`
}
