/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Registration struct {
	// Registration identifier.
	Id string `json:"id,omitempty"`
	// pending registration has not been completed successfully. accepted registration has successfully completed.
	Status string `json:"status,omitempty"`
	// Device id to be used with Verify the Factor.
	DeviceId string `json:"device_id,omitempty"`
}
