/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A dictionary of extra information that provides useful context about the session, for example the session ID, or some cookie information.
type Session struct {
	// If you use a database to track sessions, you can send us the session ID.
	Id string `json:"id,omitempty"`
}
