/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetScoreInsights200Response struct {
	Scores *GetScoreInsights200ResponseScores `json:"scores,omitempty"`
	Total int32 `json:"total,omitempty"`
}
