/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Device struct {
	DeviceId string `json:"device_id,omitempty"`
	UserDisplayName string `json:"user_display_name,omitempty"`
	TypeDisplayName string `json:"type_display_name,omitempty"`
	AuthFactorName string `json:"auth_factor_name,omitempty"`
	Default_ bool `json:"default,omitempty"`
}
