/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ErrorStatus struct {
	Code int32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
	Errors []ErrorStatusErrorsInner `json:"errors,omitempty"`
}
