/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateEnvironmentVariableRequest struct {
	// The secret value that will be encrypted at rest and injected in applicable hook functions at run time.
	Value string `json:"value"`
}
