/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A set of attributes allow control over the information that is included in the hook context.
type HookOptions struct {
	RiskEnabled bool `json:"risk_enabled,omitempty"`
	LocationEnabled bool `json:"location_enabled,omitempty"`
	MfaDeviceInfoEnabled bool `json:"mfa_device_info_enabled,omitempty"`
}
