/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListConditionOperators200ResponseInner struct {
	// The name or description of the operator.
	Name string `json:"name,omitempty"`
	// The condition operator value to use when creating or updating App Rules.
	Value string `json:"value,omitempty"`
}
