/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Role struct {
	Id int32 `json:"id,omitempty"`
	Name string `json:"name"`
	Apps []int32 `json:"apps,omitempty"`
	Users []int32 `json:"users,omitempty"`
	Admins []int32 `json:"admins,omitempty"`
}
