/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Envvar struct {
	// A unique identifier for the Hook Environment Variable
	Id string `json:"id,omitempty"`
	// The name of the environment variable.
	Name string `json:"name,omitempty"`
	// The ISO8601 formatted date that the environment variable was created.
	CreatedAt string `json:"created_at,omitempty"`
	// The ISO8601 formatted date that the environment variable was last updated.
	UpdatedAt string `json:"updated_at,omitempty"`
}
