/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RiskRule struct {
	Id string `json:"id,omitempty"`
	// The name of this rule
	Name string `json:"name,omitempty"`
	Description string `json:"description,omitempty"`
	// The type parameter specifies the type of rule that will be created.
	Type_ string `json:"type,omitempty"`
	// The target parameter that will be used when evaluating the rule against an incoming event.
	Target string `json:"target,omitempty"`
	// A list of IP addresses or country codes or names to evaluate against each event.
	Filters []string `json:"filters,omitempty"`
	Source *Source `json:"source,omitempty"`
}
