/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetAvailableFactors200ResponseInner struct {
	// Identifier for the factor which will be used for user enrollment
	FactorId int32 `json:"factor_id,omitempty"`
	// Authentication factor name, as it appears to administrators in OneLogin.
	Name string `json:"name,omitempty"`
	// Internal use only
	AuthFactorName string `json:"auth_factor_name,omitempty"`
}
