/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FactorInner struct {
	// MFA device identifier.
	Id string `json:"id,omitempty"`
	// accepted : factor has been verified. pending: registered but has not been verified.
	Status string `json:"status,omitempty"`
	// True = is user's default MFA device for OneLogin.
	Default_ bool `json:"default,omitempty"`
	// \"Official\" authentication factor name, as it appears to administrators in OneLogin.
	AuthFactorName string `json:"auth_factor_name,omitempty"`
	// Authentication factor display name as it appears to users upon initial registration, as defined by admins at Settings > Authentication Factors.
	TypeDisplayName string `json:"type_display_name,omitempty"`
	// Authentication factor display name assigned by users when they enroll the device.
	UserDisplayName string `json:"user_display_name,omitempty"`
	// A short lived token that is required to Verify the Factor. This token expires based on the expires_in parameter passed in.
	ExpiresAt string `json:"expires_at,omitempty"`
	FactorData *FactorInnerFactorData `json:"factor_data,omitempty"`
}
