/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateAuthorizationServer400Response struct {
	Field string `json:"field,omitempty"`
	Message string `json:"message,omitempty"`
	StatusCode int32 `json:"statusCode,omitempty"`
	Name string `json:"name,omitempty"`
}
