/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GetAuthorizationServer200Response struct {
	Configuration *AuthServerConfiguration `json:"configuration,omitempty"`
	Id int32 `json:"id,omitempty"`
	Description string `json:"description,omitempty"`
	Name string `json:"name,omitempty"`
}
