/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Action struct {
	// The action to apply
	Action string `json:"action,omitempty"`
	// Only applicable to provisioned and set_* actions. Items in the array will be a plain text string or valid value for the selected action.
	Value []string `json:"value,omitempty"`
	// A regular expression to extract a value. Applies to provisionable, multi-selects, and string actions.
	Expression string `json:"expression,omitempty"`
	// A hash containing scriptlet code that returns a value.
	Scriplet string `json:"scriplet,omitempty"`
	// A template to construct a value. Applies to default, string, and list actions.
	Macro string `json:"macro,omitempty"`
}
