/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Log struct {
	RequestId string `json:"request_id,omitempty"`
	CorrelationId string `json:"correlation_id,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	Events []string `json:"events,omitempty"`
}
