/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VerifyFactorRequest struct {
	// OTP code provided by the device or SMS message sent to user.
	Otp string `json:"otp,omitempty"`
	// ID of the specified device which has been registerd for the given user.
	DeviceId int32 `json:"device_id,omitempty"`
}
