/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type GenerateSamlAssertionRequest struct {
	// Set this to the username or email of the OneLogin user accessing the app for which you want to generate a SAML token.
	UsernameOrEmail string `json:"username_or_email"`
	// Password of the OneLogin user accessing the app for which you want to generate a SAML token.
	Password string `json:"password"`
	// App ID of the app for which you want to generate a SAML token. This is the app ID in OneLogin.
	AppId string `json:"app_id"`
	// Set to the subdomain of the OneLogin user accessing the app for which you want to generate a SAML token.
	Subdomain string `json:"subdomain"`
	// Whitelisted IP address, if MFA is required and you need to honor IP address whitelisting defined in MFA policies.
	IpAddress string `json:"ip_address,omitempty"`
}
