/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ListAccessTokenClaims200ResponseInner struct {
	Id int32 `json:"id,omitempty"`
	Label string `json:"label,omitempty"`
	UserAttributeMappings string `json:"user_attribute_mappings,omitempty"`
	UserAttributeMacros string `json:"user_attribute_macros,omitempty"`
	AttributesTransformations string `json:"attributes_transformations,omitempty"`
	SkipIfBlank bool `json:"skip_if_blank,omitempty"`
	Values []string `json:"values,omitempty"`
	DefaultValues string `json:"default_values,omitempty"`
	ProvisionedEntitlements bool `json:"provisioned_entitlements,omitempty"`
}
