/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SetRoleApps200ResponseInner struct {
	// Apps unique ID in OneLogin.
	Id int32 `json:"id,omitempty"`
}
