/*
 * OneLogin API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.0-alpha.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AuthServerConfiguration struct {
	Audiences []string `json:"audiences,omitempty"`
	RefreshTokenExpirationMinutes int32 `json:"refresh_token_expiration_minutes,omitempty"`
	ResourceIdentifier string `json:"resource_identifier,omitempty"`
	AccessTokenExpirationMinutes int32 `json:"access_token_expiration_minutes,omitempty"`
}
